# For development/testing only
version: '3.8'

services:
  # Database service
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scheduling_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  # NestJS API service
  nestjs-api:
    build:
      context: ./nestjs-api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scheduling_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - PORT=3001
      # Auth0 configuration - these should come from environment variables in production
      # IMPORTANT: Add these to your .env file and do NOT commit actual values to the repo
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_MANAGEMENT_CLIENT_ID=${AUTH0_MANAGEMENT_CLIENT_ID}
      - AUTH0_MANAGEMENT_CLIENT_SECRET=${AUTH0_MANAGEMENT_CLIENT_SECRET}
      # Email configuration
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run start:dev
    volumes:
      - ./nestjs-api:/app
      - /app/node_modules
      - ./uploads:/app/uploads

  # Express API service (disabled by default)
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scheduling_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - PORT=3000
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_MANAGEMENT_CLIENT_ID=${AUTH0_MANAGEMENT_CLIENT_ID}
      - AUTH0_MANAGEMENT_CLIENT_SECRET=${AUTH0_MANAGEMENT_CLIENT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        ./setup-db.sh &&
        node dist/index.js
      "
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    profiles:
      - express

  # Admin dashboard service (disabled by default)
  admin-dashboard:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./admin-dashboard/public:/usr/share/nginx/html
      - ./admin-dashboard/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VITE_API_URL=http://localhost:3001/api
    profiles:
      - admin

volumes:
  postgres_data:
  redis_data:
