version: '3.8'

services:
  express-api:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  nestjs-api:
    build:
      context: ./nestjs-api
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./nestjs-api:/app
      - /app/node_modules
    command: npm run start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
