# For development/testing only
version: '3.8'

services:
  # Database service
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scheduling_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  # API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/scheduling_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - PORT=3000
      - AUTH0_DOMAIN=itinari.us.auth0.com
      - AUTH0_AUDIENCE=https://itinari.com
      - AUTH0_CLIENT_ID=kXLq8yqzp8pZMDlathOw7ppm00p80iC6
      - AUTH0_MANAGEMENT_CLIENT_ID=kkRnHreCLRE1vD6M1Qn9vqKQ7P6swGz2 
      - AUTH0_MANAGEMENT_CLIENT_SECRET=P9hOTvDK2Qhke5vFrwmYH8450qYLEf14SeEe1Q9Qp15U4T2cIVLJ19sBqXp97S1_
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  # Admin dashboard service - temporarily using a simple nginx container until build issues are resolved
  admin-dashboard:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./admin-dashboard/public:/usr/share/nginx/html
      - ./admin-dashboard/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VITE_API_URL=http://localhost:3005/api
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
