apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scheduling-api

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

commonLabels:
  app: scheduling-api
  environment: production

configMapGenerator:
- name: scheduling-api-config
  literals:
  - NODE_ENV=production
  - PORT=3000

secretGenerator:
- name: scheduling-api-secrets
  envs:
  - .env.prod

images:
- name: scheduling-api
  newName: your-registry.example.com/scheduling-api
  newTag: latest
- name: scheduling-admin
  newName: your-registry.example.com/scheduling-admin
  newTag: latest

replicas:
- name: scheduling-api
  count: 3 