apiVersion: v1
kind: Service
metadata:
  name: scheduling-api
  namespace: scheduling-api
spec:
  selector:
    app: scheduling-api
  ports:
  - name: api
    port: 80
    targetPort: 3000
  - name: admin
    port: 8080
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scheduling-api
  namespace: scheduling-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - "*.scheduling.example.com"
    - "scheduling.example.com"
    secretName: scheduling-tls
  rules:
  - host: "api.scheduling.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scheduling-api
            port:
              number: 80
  - host: "admin.scheduling.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scheduling-api
            port:
              number: 8080
  - host: "*.scheduling.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scheduling-api
            port:
              number: 80 